name: Issue to Pull Request

on:
  issues:
    types: [opened, edited]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: cd packages/scripts && npm i --only=production
      - run: cd packages/scripts/actions && npx esno ./loader.ts ${{github.token}} issue-pr
