name: PR to Discussion

on:
  pull_request:
    types:
      - closed

jobs:
  start:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm i
      - run: cd packages/scripts/actions && npx esno ./loader.ts ${{github.token}} pr-discussion
      - uses: EndBug/add-and-commit@v9
        with:
          message: >-
           chore: create discussion for challenge ${{github.event.pull_request.title }}